import Image from "next/image"
import { MenuBar } from "@/components/menu-bar"
import { ThemeToggle } from "@/components/theme-toggle"
import Header from "./components/Header"
import "slick-carousel/slick/slick.css"
import "slick-carousel/slick/slick-theme.css"
